# .streamlit/secrets.toml

[connections.mysql]
host = "alphavue-db.cf6w82qcubk5.ap-south-1.rds.amazonaws.com"
user = "alphavue_user"
password = "TanmayElinje7099"
database = "alphavue"

[app_secrets]
admin_code = "Alphavueadmin2025"
