# .streamlit/secrets.toml

[database]
host = "alphavue-db.cf6w82qcubk5.ap-south-1.rds.amazonaws.com"
port = 3306
user = "alphavue_user"
password = "TanmayElinje7099"
db_name = "alphavue"

[app_secrets]
admin_code = "Alphavueadmin2025"
